spring:
  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_ai_db
    username: user10
    password: pass10
  jpa:
    hibernate:
      ddl-auto: update

azure:
  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
    container-name: ${AZURE_STORAGE_CONTAINER_NAME}